name: "Run k6s"
description: "k6s automation run."

inputs:
  base_url:
    description: "base url"
    required: true

  should_run_default:
    description: "should run default scripts"
    default: "false"
    required: false

runs:
  using: "composite"

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup K6
      uses: grafana/setup-k6-action@v1
      with:
        k6-version: "1.2.1"

    - name: Run dafault k6 test
      if: ${{ inputs.should_run_default == 'true' }}
      uses: grafana/run-k6-action@v1
      with:
        path: |
          ${{ github.action_path }}/k6/**/*.k6.js
      env:
        BASE_URL: ${{ inputs.base_url }}

    - name: Run local k6 tests
      uses: grafana/run-k6-action@v1
      with:
        path: |
          ./k6/**/*.k6.js
      env:
        BASE_URL: ${{ inputs.base_url }}
