name: "Run k6s"
description: "k6s automation run."

inputs:
  base_url:
    description: "base url"
    required: true

  should_run_default:
    description: "should run default scripts"
    default: "false"
    required: false

runs:
  using: "composite"

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup K6
      uses: grafana/setup-k6-action@v1
      with:
        k6-version: "1.2.1"

    - name: Parse path
      shell: bash
      id: parse_path
      run: ${{ github.action_path }}/parse_script_paths.sh
      env:
        SHOULD_RUN_DEFAULT: ${{ inputs.should_run_default == 'true' }}
        DEFAULT_PATH: ${{ github.action_path }}/k6/**/*.k6.js
        SCRIPTS: ./k6/**/*.k6.js

    - shell: bash
      run: echo "${{ steps.parse_path.outputs.path }}"

    - name: Run k6 test
      uses: grafana/run-k6-action@v1
      with:
        path: |
          ${{ steps.parse_path.outputs.path }}
      env:
        BASE_URL: ${{ inputs.base_url }}
