name: "Run k6s"
description: "k6s automation run."

inputs:
  base_url:
    description: "base url"
    required: true

runs:
  using: "composite"

  steps:
    - name: list dir
      shell: bash
      run: |
        ls -lah

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup K6
      uses: grafana/setup-k6-action@v1
      with:
        k6-version: "1.2.1"

    - name: Run local k6 test
      uses: grafana/run-k6-action@v1
      with:
        path: |
          ./default-k6/*.k6.js
          ./k6/*.k6.js
          ./k6/*.k6.ts
      env:
        BASE_URL: ${{ inputs.base_url }}
