name: "Run k6s"
description: "k6s automation run."

inputs:
  base_url:
    description: "base url"
    required: true

  should_run_default:
    description: "should run default scripts"
    default: "false"
    required: false

runs:
  using: "composite"

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup K6
      uses: grafana/setup-k6-action@v1
      with:
        k6-version: "1.2.1"

    - name: Setup node
      uses: actions/setup-node@v4

    - name: Setup reports dir
      shell: bash
      run: |
        mkdir -p ./{reports,output-report}

    - name: Run default k6 test
      if: ${{ inputs.should_run_default == 'true' }}
      uses: grafana/run-k6-action@v1
      with:
        path: |
          ${{ github.action_path }}/k6/**/*.k6.js
      env:
        BASE_URL: ${{ inputs.base_url }}
        REPORTS_PATH: ./reports

    - name: Run k6 test
      uses: grafana/run-k6-action@v1
      with:
        path: |
          ./k6/**/*.k6.js
      env:
        BASE_URL: ${{ inputs.base_url }}
        REPORTS_PATH: ./reports

    - name: Merge results and generate report
      shell: bash
      run: node ${{ github.action_path }}/reports/index.js
      env:
        REPORTS_PATH: ./reports
        EXPORT_REPORT_PATH: ./output-report

    - name: Move reports to output folder
      shell: bash
      run: |
        mv ./reports/* ./output-report

    - name: Upload report to artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: k6-results
        path: output-report

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: k6-results

    - name: echo deploy page
      shell: bash
      run: echo ${{ steps.deployment.outputs.page_url }}
