networks:
  k6:

services:
  k6:
    image: grafana/k6:latest
    container_name: k6
    working_dir: /usr/src/k6
    entrypoint: ./entrypoint.sh
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - BASE_URL=${BASE_URL}
      - REPORTS_PATH=/reports
    volumes:
      - ./k6:/usr/src/k6
      - ./reports:/reports

  report:
    image: node:24-alpine3.21
    container_name: report
    working_dir: /usr/src/report
    command: node index.js
    environment:
      - REPORTS_PATH=./
      - EXPORT_REPORT_PATH=./
    volumes:
      - ./reports:/usr/src/report
