volumes:
  prometheus-storage:
  grafana-storage:

networks:
  k6:
  grafana:
  influxdb:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
    networks:
      - k6
      - grafana

  grafana:
    image: grafana/grafana:11.5
    container_name: grafana
    networks:
      - grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus

  k6:
    image: grafana/k6:latest
    container_name: k6
    working_dir: /usr/src/k6
    entrypoint: ./entrypoint.sh
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - BASE_URL=${BASE_URL}
      - REPORTS_PATH=/reports
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=p(95),p(99),min,max
    volumes:
      - ./k6:/usr/src/k6
      - ./reports:/reports
    depends_on:
      - prometheus

  report:
    image: node:24-alpine3.21
    container_name: report
    working_dir: /usr/src/report
    command: node index.js
    environment:
      - REPORTS_PATH=./
      - EXPORT_REPORT_PATH=./
    volumes:
      - ./reports:/usr/src/report
