import { readdirSync, writeFileSync } from "fs"

const REPORTS_PATH = process.env.REPORTS_PATH
const EXPORT_REPORT_PATH = process.env.EXPORT_REPORT_PATH

function validateIfFileIsReport(fielName) {
  const validateRegex = new RegExp(/^report(.*).html$/gm)

  const isReport = validateRegex.test(fielName)

  return isReport
}

function parseReportName(fileName) {
  const regex = /report-(.*).html/gm

  const [_, reportName] = regex.exec(fileName)

  return reportName
}

function htmlReport(fileNames) {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>K6 Test Reports</title>
  <style>
    body {
      font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }

    header {
      background-color: #1a73e8;
      color: white;
      padding: 20px;
      text-align: center;
    }

    main {
      max-width: 900px;
      margin: 30px auto;
      padding: 20px;
      background-color: white;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
      border-radius: 8px;
    }

    h1 {
      margin-top: 0;
    }

    table {
      width: 100%;
      border-collapse: collapse;
    }

    th, td {
      text-align: left;
      padding: 12px 16px;
    }

    th {
      background-color: #f0f0f0;
    }

    tr:nth-child(even) {
      background-color: #fafafa;
    }

    a.report-link {
      color: #1a73e8;
      text-decoration: none;
    }

    a.report-link:hover {
      text-decoration: underline;
    }

    footer {
      text-align: center;
      font-size: 0.9em;
      color: #666;
      padding: 20px;
    }
  </style>
</head>
<body>

  <header>
    <h1>K6 Performance Test Reports</h1>
    <p>Select a report to view detailed metrics</p>
  </header>

  <main>
    <table>
      <thead>
        <tr>
          <th>Report Name</th>
          <th>Link</th>
        </tr>
      </thead>
      <tbody>
        ${fileNames
          .map(
            (item, index) => `
          <tr>
            <td>Test Run ${parseReportName(item)} #${index + 1}</td>
            <td><a class="report-link" href="${item}" target="_blank">View Report</a></td>
          </tr>
        `
          )
          .join("\n")}
      </tbody>
    </table>
  </main>

  <footer>
    Generated by K6 | Report Index Page
  </footer>

</body>
</html>
  `
  return html
}

;(function main() {
  const filesName = readdirSync(REPORTS_PATH)

  const reportsFileName = filesName.filter(validateIfFileIsReport)

  const htmlIndex = htmlReport(reportsFileName)

  writeFileSync(`${EXPORT_REPORT_PATH}/index.html`, htmlIndex)
})()
